split_mode = [
    'IL',
    2,
]

[[splits]]
name = 'Mirror'
chapter = 2

[splits.split_kind]
kind = 'Level'
kind_data = 'd3'

[[splits]]
name = 'Start Exit'
chapter = 2

[splits.split_kind]
kind = 'Level'
kind_data = '3'

[[splits]]
name = 'That coin room'
chapter = 2

[splits.split_kind]
kind = 'Level'
kind_data = '7'

[[splits]]
name = 'Fally'
chapter = 2

[splits.split_kind]
kind = 'Level'
kind_data = '10'

[[splits]]
name = 'Awake'
chapter = 2

[splits.split_kind]
kind = 'Level'
kind_data = 'end_0'

[[splits]]
name = 'UwU PB pls'
chapter = 2

[splits.split_kind]
kind = 'ChapterComplete'
